### ISSUE TITLE
Pickle files missing input variables

### ISSUE THREAD

**Issue by jacquelinedowling** [ClabEnergyProject/SEM-1.2#11] opened 2019-10-11 17:29 UTC
The pickle files seem to be missing the input variables (fixed are var costs for ex).

Usually the pickle file is a list of three things 1. info, 2. input variables, 3. results variables
The second item (input variables) in the list is missing. It is just a list of zeros. No dictionary of variables like there used to be in SEM 1.1.

**Comment by truggles** [comment] 2019-10-14 19:03
I don’t see that behavior in the one file I looked at (see below).  I checked the pickle file from the test case csv file `case_input_test_191008.csv`.  If I add another line to the commands below:
`print(d[1])` it prints all the info for the inputs.  Can you try and reproduce what I have by starting with the head of the master branch?

>>> import pickle
>>> pickle_in = open(‘test_190926_EIAbase.pickle’, ‘rb’)
>>> d = pickle.load(pickle_in)
>>> print(d[0].keys())
dict_keys([‘NUM_CASES’, ‘QUICK_LOOK’, ‘GLOBAL_NAME’, ‘DATA_PATH’, ‘OUTPUT_PATH’, ‘VERBOSE’, ‘POSTPROCESS’])
>>> print(d[1].keys())
dict_keys([‘CO2_PRICE’, ‘FIXED_COST_NATGAS’, ‘VAR_COST_NATGAS’, ‘FIXED_CO2_NATGAS’, ‘VAR_CO2_NATGAS’, ‘FIXED_COST_NATGAS_CCS’, ‘VAR_COST_NATGAS_CCS’, ‘FIXED_CO2_NATGAS_CCS’, ‘VAR_CO2_NATGAS_CCS’, ‘FIXED_COST_SOLAR’, ‘VAR_COST_SOLAR’, ‘FIXED_CO2_SOLAR’, ‘VAR_CO2_SOLAR’, ‘FIXED_COST_SOLAR2’, ‘VAR_COST_SOLAR2’, ‘FIXED_CO2_SOLAR2’, ‘VAR_CO2_SOLAR2’, ‘FIXED_COST_WIND’, ‘VAR_COST_WIND’, ‘FIXED_CO2_WIND’, ‘VAR_CO2_WIND’, ‘FIXED_COST_WIND2’, ‘VAR_COST_WIND2’, ‘FIXED_CO2_WIND2’, ‘VAR_CO2_WIND2’, ‘FIXED_COST_NUCLEAR’, ‘VAR_COST_NUCLEAR’, ‘FIXED_CO2_NUCLEAR’, ‘VAR_CO2_NUCLEAR’, ‘FIXED_COST_STORAGE’, ‘VAR_COST_STORAGE’, ‘VAR_COST_TO_STORAGE’, ‘VAR_COST_FROM_STORAGE’, ‘FIXED_COST_STORAGE2’, ‘VAR_COST_STORAGE2’, ‘VAR_COST_TO_STORAGE2’, ‘VAR_COST_FROM_STORAGE2’, ‘FIXED_COST_PGP_STORAGE’, ‘FIXED_COST_TO_PGP_STORAGE’, ‘FIXED_COST_FROM_PGP_STORAGE’, ‘VAR_COST_TO_PGP_STORAGE’, ‘VAR_COST_FROM_PGP_STORAGE’, ‘FIXED_COST_CSP’, ‘VAR_COST_CSP’, ‘FIXED_COST_CSP_STORAGE’, ‘VAR_COST_CSP_STORAGE’, ‘VAR_COST_UNMET_DEMAND’, ‘NUMERICS_COST_SCALING’, ‘NUMERICS_DEMAND_SCALING’, ‘END_DAY’, ‘END_HOUR’, ‘END_MONTH’, ‘END_YEAR’, ‘START_DAY’, ‘START_HOUR’, ‘START_MONTH’, ‘START_YEAR’, ‘CAPACITY_NATGAS’, ‘CAPACITY_NATGAS_CCS’, ‘CAPACITY_SOLAR’, ‘CAPACITY_SOLAR2’, ‘CAPACITY_WIND’, ‘CAPACITY_WIND2’, ‘CAPACITY_NUCLEAR’, ‘CAPACITY_STORAGE’, ‘CHARGING_TIME_STORAGE’, ‘CHARGING_EFFICIENCY_STORAGE’, ‘DECAY_RATE_STORAGE’, ‘CAPACITY_STORAGE2’, ‘CHARGING_TIME_STORAGE2’, ‘CHARGING_EFFICIENCY_STORAGE2’, ‘DECAY_RATE_STORAGE2’, ‘CAPACITY_PGP_STORAGE’, ‘CAPACITY_TO_PGP_STORAGE’, ‘CAPACITY_FROM_PGP_STORAGE’, ‘CHARGING_EFFICIENCY_PGP_STORAGE’, ‘DECAY_RATE_PGP_STORAGE’, ‘CAPACITY_CSP’, ‘CAPACITY_CSP_STORAGE’, ‘DECAY_RATE_CSP_STORAGE’, ‘CHARGING_EFFICIENCY_CSP_STORAGE’, ‘SYSTEM_RELIABILITY’, ‘DATA_PATH’, ‘DEMAND_FILE’, ‘SOLAR2_CAPACITY_FILE’, ‘WIND2_CAPACITY_FILE’, ‘SOLAR_CAPACITY_FILE’, ‘WIND_CAPACITY_FILE’, ‘CSP_CAPACITY_FILE’, ‘OUTPUT_PATH’, ‘CASE_NAME’, ‘GLOBAL_NAME’, ‘NORMALIZE_DEMAND_TO_ONE’, ‘SYSTEM_COMPONENTS’, ‘DEMAND_SERIES’, ‘WIND_SERIES’, ‘SOLAR_SERIES’, ‘WIND2_SERIES’, ‘SOLAR2_SERIES’, ‘CSP_SERIES’])
>>> print(d[2].keys())
dict_keys([‘SYSTEM_COST’, ‘PROBLEM_STATUS’, ‘PRICE’, ‘CAPACITY_NATGAS’, ‘DISPATCH_NATGAS’, ‘CAPACITY_NATGAS_CCS’, ‘DISPATCH_NATGAS_CCS’, ‘CAPACITY_SOLAR’, ‘DISPATCH_SOLAR’, ‘CURTAILMENT_SOLAR’, ‘CAPACITY_WIND’, ‘DISPATCH_WIND’, ‘CURTAILMENT_WIND’, ‘CAPACITY_SOLAR2’, ‘DISPATCH_SOLAR2’, ‘CURTAILMENT_SOLAR2’, ‘CAPACITY_WIND2’, ‘DISPATCH_WIND2’, ‘CURTAILMENT_WIND2’, ‘CAPACITY_NUCLEAR’, ‘DISPATCH_NUCLEAR’, ‘CURTAILMENT_NUCLEAR’, ‘CAPACITY_STORAGE’, ‘DISPATCH_TO_STORAGE’, ‘DISPATCH_FROM_STORAGE’, ‘ENERGY_STORAGE’, ‘CAPACITY_STORAGE2’, ‘DISPATCH_TO_STORAGE2’, ‘DISPATCH_FROM_STORAGE2’, ‘ENERGY_STORAGE2’, ‘CAPACITY_PGP_STORAGE’, ‘CAPACITY_TO_PGP_STORAGE’, ‘CAPACITY_FROM_PGP_STORAGE’, ‘DISPATCH_TO_PGP_STORAGE’, ‘DISPATCH_FROM_PGP_STORAGE’, ‘ENERGY_PGP_STORAGE’, ‘CAPACITY_CSP’, ‘CAPACITY_CSP_STORAGE’, ‘DISPATCH_TO_CSP_STORAGE’, ‘DISPATCH_FROM_CSP’, ‘ENERGY_CSP_STORAGE’, ‘CURTAILMENT_CSP’, ‘DISPATCH_UNMET_DEMAND’])

**Comment by KatherineRinaldi** [comment] 2019-10-15 18:24
I am fairly sure this has been resolved. I got the same results as you, Tyler, I think it just originally looked like the inputs were an array of 0's because it used to print truncated lists and now it prints the whole thing so you have to scroll up to see that it's the full dictionary. @jacquelinedowling it's working for you now, right?

**Comment by truggles** [comment] 2019-10-15 20:14
Closing this.  The pickle files were not missing info.

**Closed as completed by truggles** 2019-10-15 20:14 UTC
